
export const ALL_SKILLS = [
  // Programming Languages
  "JavaScript",
  "Python",
  "Java",
  "TypeScript",
  "C#",
  "C++",
  "PHP",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "Ruby",
  "Scala",
  "R",
  "SQL",
  "NoSQL",
  "HTML",
  "CSS",
  "Dart",

  // Frontend Frameworks & Libraries
  "React",
  "Angular",
  "Vue.js",
  "Svelte",
  "Next.js",
  "Gatsby",
  "Nuxt.js",
  "jQuery",
  "Bootstrap",
  "Tailwind CSS",
  "Sass",
  "LESS",
  "Redux",
  "MobX",
  "GraphQL",
  "Apollo Client",
  "Framer Motion",
  "GSAP",

  // Backend Frameworks & Libraries
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Ruby on Rails",
  "Spring Boot",
  "ASP.NET",
  "Laravel",
  "Phoenix",

  // Mobile Development
  "React Native",
  "Flutter",
  "Swift (iOS)",
  "Kotlin (Android)",
  "Java (Android)",
  "Xamarin",

  // Databases
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Firebase Firestore",
  "SQLite",
  "Microsoft SQL Server",
  "Oracle",
  
  // DevOps & Cloud
  "Docker",
  "Kubernetes",
  "AWS",
  "Google Cloud Platform (GCP)",
  "Microsoft Azure",
  "Terraform",
  "Ansible",
  "Jenkins",
  "Git",
  "GitHub Actions",
  "CI/CD",
  "Linux",
  "Bash Scripting",
  "PowerShell",

  // AI & Machine Learning
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "Pandas",
  "NumPy",
  "Keras",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Data Science",
  "Genkit",
  "Firebase Genkit",
  
  // Web3 & Blockchain
  "Solidity",
  "Web3.js",
  "Ethers.js",
  "Hardhat",
  "Truffle",
  "Smart Contracts",
  "IPFS",

  // Design & UI/UX
  "Figma",
  "Adobe XD",
  "Sketch",
  "UI Design",
  "UX Design",
  "Design Systems",
  "Prototyping",
  "User Research",

  // Other
  "Project Management",
  "Agile Methodologies",
  "Scrum",
  "Public Speaking",
  "Technical Writing",
  "Content Creation",
  "API Design",
  "System Design",
  "Web Assembly",
  "Cybersecurity",
  "Penetration Testing"
];
